name: Release on Tag

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build project
      run: |
        # 这里运行你的构建命令，例如：
        npm install
        npm run build
        echo "Building project..."

    - name: Create ZIP file
      run: |
        cd dist
        zip -r release.zip .

    - name: Upload Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        files: dist/release.zip
        tag_name: ${{ github.ref }}
        release_name: "Release ${{ github.ref }}"
        body: ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
