name: Release Compilation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            runtime: linux-x64
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'
        
    - name: Build
      run: |
        npm install
        npm run build
      timeout-minutes: 10 
        
    - name: Zip the build output
      run: |
        cd dist
        zip -r "./release.zip" .
      timeout-minutes: 5
      shell: pwsh
      
    - name: Upload
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      with:
        files: dist/*